#ifndef SHORTCUTKEYBINDER_GLOBAL_H
#define SHORTCUTKEYBINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHORTCUTKEYBINDER_LIBRARY)
#  define SHORTCUTKEYBINDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHORTCUTKEYBINDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHORTCUTKEYBINDER_GLOBAL_H
