#ifndef HOTKEYBINDER_GLOBAL_H
#define HOTKEYBINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOTKEYBINDER_LIBRARY)
#  define HOTKEYBINDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOTKEYBINDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOTKEYBINDER_GLOBAL_H
